services:
  strongswan:
    container_name: strongswan

    image: lkpot/strongswan:latest

    network_mode: host

    cap_add:
      - NET_ADMIN

    expose:
      - "500"
      - "4500"

    user: ${UID}:${GID}

    volumes:
      - ./etc-strongswan:/etc/strongswan

    restart: unless-stopped
