services:
  strongswan:
    container_name: strongswan

    image: lkpot/strongswan:latest

    network_mode: host

    cap_drop:
      - ALL

    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE

    expose:
      - "500"
      - "4500"

    user: ${UID}:${GID}

    volumes:
      - ./swanctl:/etc/strongswan/swanctl

    restart: unless-stopped
